// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantityMeasurementAppRepositories.Context;

#nullable disable

namespace QuantityMeasurementAppRepositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ==================== QuantityMeasurementEntity ====================
            modelBuilder.Entity("QuantityMeasurementAppModels.Entities.QuantityMeasurementEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasColumnName("created_at");
                b.Property<string>("ErrorMessage").HasMaxLength(500).HasColumnType("nvarchar(500)").HasColumnName("error_message");
                b.Property<double>("FirstValue").HasColumnType("float").HasColumnName("first_value");
                b.Property<string>("FirstUnit").HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("first_unit");
                b.Property<bool>("IsError").HasColumnType("bit").HasColumnName("is_error");
                b.Property<string>("MeasurementType").HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("measurement_type");
                b.Property<string>("Operation").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("operation");
                b.Property<double>("ResultValue").HasColumnType("float").HasColumnName("result_value");
                b.Property<double>("SecondValue").HasColumnType("float").HasColumnName("second_value");
                b.Property<string>("SecondUnit").HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("second_unit");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2").HasColumnName("updated_at");

                b.HasKey("Id");
                b.HasIndex("IsError").HasDatabaseName("IX_quantity_measurements_is_error");
                b.HasIndex("MeasurementType").HasDatabaseName("IX_quantity_measurements_measurement_type");
                b.HasIndex("Operation").HasDatabaseName("IX_quantity_measurements_operation");
                b.ToTable("quantity_measurements");
            });

            // ==================== UserEntity ====================
            modelBuilder.Entity("QuantityMeasurementAppModels.Entities.UserEntity", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("FailedLoginAttempts").HasColumnType("int").HasDefaultValue(0);
                b.Property<string>("FirstName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
                b.Property<DateTime?>("LockoutEnd").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasDefaultValue("User");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            // ==================== RefreshTokenEntity ====================
            modelBuilder.Entity("QuantityMeasurementAppModels.Entities.RefreshTokenEntity", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedByIp").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                b.Property<string>("ReplacedByToken").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                b.Property<string>("RevokedByIp").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Token").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<long>("UserId").HasColumnType("bigint");

                b.HasKey("Id");
                b.HasIndex("Token").IsUnique();
                b.HasIndex("UserId");
                b.HasIndex("ExpiresAt");
                b.ToTable("RefreshTokens");
            });

            // ==================== Relationships ====================
            modelBuilder.Entity("QuantityMeasurementAppModels.Entities.RefreshTokenEntity", b =>
            {
                b.HasOne("QuantityMeasurementAppModels.Entities.UserEntity", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("QuantityMeasurementAppModels.Entities.UserEntity", b =>
            {
                b.Navigation("RefreshTokens");
            });

#pragma warning restore 612, 618
        }
    }
}
